# Generated by Django 5.0.6 on 2024-05-19 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('contact_person', models.CharField(max_length=100)),
                ('collaboration_status', models.CharField(choices=[('NC', 'Not contacted'), ('DI', 'In discussion'), ('CC', 'The deal is closed'), ('RE', 'Rejection')], max_length=2)),
                ('deal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('content_count', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
