# Generated by Django 5.0.6 on 2024-05-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contacted_via',
            field=models.CharField(choices=[('EM', 'Email'), ('IN', 'Instagram'), ('TT', 'TikTok'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
