# Generated by Django 5.0.6 on 2024-05-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0002_company_contacted_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contacted_via',
            field=models.CharField(choices=[('NC', 'Email'), ('DI', 'Instagram'), ('CC', 'TikTok'), ('RE', 'Other')], default='OT', max_length=2),
        ),
    ]
