# Generated by Django 5.0.6 on 2024-05-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='niche',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
