# Generated by Django 5.0.6 on 2024-05-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0008_alter_company_niche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
