# Generated by Django 5.0.6 on 2024-05-24 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0009_alter_company_email_alter_company_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.AlterField(
            model_name='company',
            name='collaboration_status',
            field=models.CharField(choices=[('NC', 'Not contacted'), ('DI', 'In discussion'), ('CC', 'The deal is closed'), ('RE', 'Rejection')], default='NC', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='contacted_via',
            field=models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Social Media', 'Social Media'), ('In Person', 'In Person'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='niche',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Finance', 'Finance'), ('Health', 'Health'), ('Education', 'Education'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
