# Generated by Django 5.0.6 on 2024-05-24 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0010_remove_company_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='collaboration_status',
            field=models.CharField(choices=[('NC', 'Not contacted'), ('DI', 'In discussion'), ('CC', 'The deal is closed'), ('RE', 'Rejection')], max_length=2),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person',
            field=models.CharField(default='manager', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='contacted_via',
            field=models.CharField(choices=[('NC', 'Email'), ('DI', 'Instagram'), ('CC', 'TikTok'), ('RE', 'Other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='niche',
            field=models.CharField(choices=[('EC', 'Electronics & Computers'), ('FU', 'Furniture'), ('HP', 'Home Products'), ('CS', 'Cosmetics, skin & hair care'), ('TC', 'Toys and products for children'), ('CL', 'Clothes and shoes'), ('SH', 'Sports and hobbies'), ('FD', 'Food and drink'), ('OT', 'Others')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
