# Generated by Django 5.0.6 on 2024-05-28 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_service', '0011_company_logo_alter_company_collaboration_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('goal', models.CharField(choices=[('3', '3 successfully closed deals'), ('5', '5 successfully closed deals'), ('7', '7 successfully closed deals'), ('10', '10 successfully closed deals')], default='5', max_length=2)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration_status', models.CharField(choices=[('NC', 'Not contacted'), ('DI', 'In discussion'), ('CC', 'The deal is closed'), ('RE', 'Rejection')], default='NC', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_service.company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='companies',
            field=models.ManyToManyField(through='user_profile.ProfileCompany', to='company_service.company'),
        ),
    ]
