# Generated by Django 5.0.6 on 2024-05-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0011_company_logo_alter_company_collaboration_status_and_more'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='companies',
            field=models.ManyToManyField(related_name='profiles', through='user_profile.ProfileCompany', to='company_service.company'),
        ),
    ]
