# Generated by Django 5.0.6 on 2024-05-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecompany',
            name='content_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilecompany',
            name='deal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
