# Generated by Django 5.0.6 on 2024-06-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_profilecompany_custom_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('3', '3 successfully closed deals'), ('5', '5 successfully closed deals'), ('7', '7 successfully closed deals'), ('10', '10 successfully closed deals'), ('15', '15 successfully closed deals'), ('25', '25 successfully closed deals'), ('50', '50 successfully closed deals'), ('75', '75 successfully closed deals'), ('100', '100 successfully closed deals')], default='5', max_length=3),
        ),
    ]
